package com.jpm.datasource_remote.util

const val validJsonResponse = "{\n" +
        "\"count\":60,\n" +
        "\"next\":\"https://swapi.dev/api/planets/?page=5\",\n" +
        "\"previous\":\"https://swapi.dev/api/planets/?page=3\",\n" +
        "\"results\":[\n" +
        "{\n" +
        "\"name\":\"Mon Cala\",\n" +
        "\"rotation_period\":\"21\",\n" +
        "\"orbital_period\":\"398\",\n" +
        "\"diameter\":\"11030\",\n" +
        "\"climate\":\"temperate\",\n" +
        "\"gravity\":\"1\",\n" +
        "\"terrain\":\"oceans, reefs, islands\",\n" +
        "\"surface_water\":\"100\",\n" +
        "\"population\":\"27000000000\",\n" +
        "\"residents\":[\n" +
        "\"https://swapi.dev/api/people/27/\"\n" +
        "],\n" +
        "\"films\":[\n" +
        "],\n" +
        "\"created\":\"2014-12-18T11:07:01.792000Z\",\n" +
        "\"edited\":\"2014-12-20T20:58:18.471000Z\",\n" +
        "\"url\":\"https://swapi.dev/api/planets/31/\"\n" +
        "},\n" +
        "{\n" +
        "\"name\":\"Chandrila\",\n" +
        "\"rotation_period\":\"20\",\n" +
        "\"orbital_period\":\"368\",\n" +
        "\"diameter\":\"13500\",\n" +
        "\"climate\":\"temperate\",\n" +
        "\"gravity\":\"1\",\n" +
        "\"terrain\":\"plains, forests\",\n" +
        "\"surface_water\":\"40\",\n" +
        "\"population\":\"1200000000\",\n" +
        "\"residents\":[\n" +
        "\"https://swapi.dev/api/people/28/\"\n" +
        "],\n" +
        "\"films\":[\n" +
        "],\n" +
        "\"created\":\"2014-12-18T11:11:51.872000Z\",\n" +
        "\"edited\":\"2014-12-20T20:58:18.472000Z\",\n" +
        "\"url\":\"https://swapi.dev/api/planets/32/\"\n" +
        "},\n" +
        "{\n" +
        "\"name\":\"Sullust\",\n" +
        "\"rotation_period\":\"20\",\n" +
        "\"orbital_period\":\"263\",\n" +
        "\"diameter\":\"12780\",\n" +
        "\"climate\":\"superheated\",\n" +
        "\"gravity\":\"1\",\n" +
        "\"terrain\":\"mountains, volcanoes, rocky deserts\",\n" +
        "\"surface_water\":\"5\",\n" +
        "\"population\":\"18500000000\",\n" +
        "\"residents\":[\n" +
        "\"https://swapi.dev/api/people/31/\"\n" +
        "],\n" +
        "\"films\":[\n" +
        "],\n" +
        "\"created\":\"2014-12-18T11:25:40.243000Z\",\n" +
        "\"edited\":\"2014-12-20T20:58:18.474000Z\",\n" +
        "\"url\":\"https://swapi.dev/api/planets/33/\"\n" +
        "},\n" +
        "{\n" +
        "\"name\":\"Toydaria\",\n" +
        "\"rotation_period\":\"21\",\n" +
        "\"orbital_period\":\"184\",\n" +
        "\"diameter\":\"7900\",\n" +
        "\"climate\":\"temperate\",\n" +
        "\"gravity\":\"1\",\n" +
        "\"terrain\":\"swamps, lakes\",\n" +
        "\"surface_water\":\"unknown\",\n" +
        "\"population\":\"11000000\",\n" +
        "\"residents\":[\n" +
        "\"https://swapi.dev/api/people/40/\"\n" +
        "],\n" +
        "\"films\":[\n" +
        "],\n" +
        "\"created\":\"2014-12-19T17:47:54.403000Z\",\n" +
        "\"edited\":\"2014-12-20T20:58:18.476000Z\",\n" +
        "\"url\":\"https://swapi.dev/api/planets/34/\"\n" +
        "},\n" +
        "{\n" +
        "\"name\":\"Malastare\",\n" +
        "\"rotation_period\":\"26\",\n" +
        "\"orbital_period\":\"201\",\n" +
        "\"diameter\":\"18880\",\n" +
        "\"climate\":\"arid, temperate, tropical\",\n" +
        "\"gravity\":\"1.56\",\n" +
        "\"terrain\":\"swamps, deserts, jungles, mountains\",\n" +
        "\"surface_water\":\"unknown\",\n" +
        "\"population\":\"2000000000\",\n" +
        "\"residents\":[\n" +
        "\"https://swapi.dev/api/people/41/\"\n" +
        "],\n" +
        "\"films\":[\n" +
        "],\n" +
        "\"created\":\"2014-12-19T17:52:13.106000Z\",\n" +
        "\"edited\":\"2014-12-20T20:58:18.478000Z\",\n" +
        "\"url\":\"https://swapi.dev/api/planets/35/\"\n" +
        "},\n" +
        "{\n" +
        "\"name\":\"Dathomir\",\n" +
        "\"rotation_period\":\"24\",\n" +
        "\"orbital_period\":\"491\",\n" +
        "\"diameter\":\"10480\",\n" +
        "\"climate\":\"temperate\",\n" +
        "\"gravity\":\"0.9\",\n" +
        "\"terrain\":\"forests, deserts, savannas\",\n" +
        "\"surface_water\":\"unknown\",\n" +
        "\"population\":\"5200\",\n" +
        "\"residents\":[\n" +
        "\"https://swapi.dev/api/people/44/\"\n" +
        "],\n" +
        "\"films\":[\n" +
        "],\n" +
        "\"created\":\"2014-12-19T18:00:40.142000Z\",\n" +
        "\"edited\":\"2014-12-20T20:58:18.480000Z\",\n" +
        "\"url\":\"https://swapi.dev/api/planets/36/\"\n" +
        "},\n" +
        "{\n" +
        "\"name\":\"Ryloth\",\n" +
        "\"rotation_period\":\"30\",\n" +
        "\"orbital_period\":\"305\",\n" +
        "\"diameter\":\"10600\",\n" +
        "\"climate\":\"temperate, arid, subartic\",\n" +
        "\"gravity\":\"1\",\n" +
        "\"terrain\":\"mountains, valleys, deserts, tundra\",\n" +
        "\"surface_water\":\"5\",\n" +
        "\"population\":\"1500000000\",\n" +
        "\"residents\":[\n" +
        "\"https://swapi.dev/api/people/45/\",\n" +
        "\"https://swapi.dev/api/people/46/\"\n" +
        "],\n" +
        "\"films\":[\n" +
        "],\n" +
        "\"created\":\"2014-12-20T09:46:25.740000Z\",\n" +
        "\"edited\":\"2014-12-20T20:58:18.481000Z\",\n" +
        "\"url\":\"https://swapi.dev/api/planets/37/\"\n" +
        "},\n" +
        "{\n" +
        "\"name\":\"Aleen Minor\",\n" +
        "\"rotation_period\":\"unknown\",\n" +
        "\"orbital_period\":\"unknown\",\n" +
        "\"diameter\":\"unknown\",\n" +
        "\"climate\":\"unknown\",\n" +
        "\"gravity\":\"unknown\",\n" +
        "\"terrain\":\"unknown\",\n" +
        "\"surface_water\":\"unknown\",\n" +
        "\"population\":\"unknown\",\n" +
        "\"residents\":[\n" +
        "\"https://swapi.dev/api/people/47/\"\n" +
        "],\n" +
        "\"films\":[\n" +
        "],\n" +
        "\"created\":\"2014-12-20T09:52:23.452000Z\",\n" +
        "\"edited\":\"2014-12-20T20:58:18.483000Z\",\n" +
        "\"url\":\"https://swapi.dev/api/planets/38/\"\n" +
        "},\n" +
        "{\n" +
        "\"name\":\"Vulpter\",\n" +
        "\"rotation_period\":\"22\",\n" +
        "\"orbital_period\":\"391\",\n" +
        "\"diameter\":\"14900\",\n" +
        "\"climate\":\"temperate, artic\",\n" +
        "\"gravity\":\"1\",\n" +
        "\"terrain\":\"urban, barren\",\n" +
        "\"surface_water\":\"unknown\",\n" +
        "\"population\":\"421000000\",\n" +
        "\"residents\":[\n" +
        "\"https://swapi.dev/api/people/48/\"\n" +
        "],\n" +
        "\"films\":[\n" +
        "],\n" +
        "\"created\":\"2014-12-20T09:56:58.874000Z\",\n" +
        "\"edited\":\"2014-12-20T20:58:18.485000Z\",\n" +
        "\"url\":\"https://swapi.dev/api/planets/39/\"\n" +
        "},\n" +
        "{\n" +
        "\"name\":\"Troiken\",\n" +
        "\"rotation_period\":\"unknown\",\n" +
        "\"orbital_period\":\"unknown\",\n" +
        "\"diameter\":\"unknown\",\n" +
        "\"climate\":\"unknown\",\n" +
        "\"gravity\":\"unknown\",\n" +
        "\"terrain\":\"desert, tundra, rainforests, mountains\",\n" +
        "\"surface_water\":\"unknown\",\n" +
        "\"population\":\"unknown\",\n" +
        "\"residents\":[\n" +
        "\"https://swapi.dev/api/people/49/\"\n" +
        "],\n" +
        "\"films\":[\n" +
        "],\n" +
        "\"created\":\"2014-12-20T10:01:37.395000Z\",\n" +
        "\"edited\":\"2014-12-20T20:58:18.487000Z\",\n" +
        "\"url\":\"https://swapi.dev/api/planets/40/\"\n" +
        "}\n" +
        "]\n" +
        "}"